/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.Clientes_controller;
import Controller.Conexao;
import Controller.ItemVendas_controller;
import Controller.Produtos_controller;
import Controller.Vendas_controller;
import Models.Clientes_model;
import Models.ItemVendas_model;
import Models.Produtos_model;
import Models.Vendas_model;
import Models.item_prod;
import com.sun.media.sound.ModelOscillator;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Venda extends javax.swing.JFrame {
    
    int cod=0,id=0, id_cli, qt=0,quant=0;;
    double totalpag=0, totalparc=0;
    
    ArrayList<item_prod> list_pro = new ArrayList<item_prod>();
    int x=0;
    Conexao c = new Conexao();
    int cont=0;

    /**
     * Creates new form Venda
     */
    public Venda() {
        initComponents();
        x = 1;
        busca(); 
        busca2();  
        busca3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbProduto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfVT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfQtde = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        tfCod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Caixa 1");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Cliente");

        jLabel3.setText("Produto");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar Venda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfVT.setEditable(false);
        tfVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVTActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor Total (R$)");

        jLabel5.setText("Quantidade");

        tfQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdeActionPerformed(evt);
            }
        });

        jLabel6.setText("Data");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfCod.setEditable(false);

        jLabel7.setText("Código");

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel4)
                                .addGap(81, 81, 81)
                                .addComponent(tfVT, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel2)
                                                .addGap(17, 17, 17)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(tfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(37, 37, 37))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(tfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtdeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Produtos_model p1 = new Produtos_model();
        Vendas_model v = new Vendas_model();
        ItemVendas_model iv = new ItemVendas_model();
        
        if(x==1){ // primeira vez salva depois só altera
            v.setIdvenda(cod);
            v.setIdCliente(busca5());
            v.setTotalpagar(totalpag);

        try { 
            DateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            v.setData(new java.sql.Date(((java.util.Date) formatador.parse(jFormattedTextField1.getText())).getTime()));
           } catch (ParseException ex) {
               Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
           }

            Vendas_controller ven = new Vendas_controller();
            ven.salvar(v);
        }
        x++;
       
       
        iv.setIdProduto(busca4()); // chama o metodo para pegar o idproduto para salvar na tabela itemvenda
        iv.setIdVenda(Integer.parseInt(tfCod.getText()));
        iv.setQtde(Integer.parseInt(tfQtde.getText()));
        iv.setTotalparc(totalparc);
          
        p1.setIdProduto(iv.getIdProduto());
        qt = quant - iv.getQtde();
        
        if(qt < 0){
           JOptionPane.showMessageDialog(null, "Não há estoque suficiente!!!!", "Vendas", 1);
           cbProduto.setSelectedIndex(0);
           tfVT.setText("");
           
           dispose();
           Menu x = new Menu();
           x.setVisible(true);
          
        }else if(qt <= 8 && qt > 0){
            p1.setQauntidade(qt);
            
            ItemVendas_controller item = new ItemVendas_controller();
            item.salvar(iv);
            
            Produtos_controller p = new Produtos_controller();
            p.alterar(p1);
            
            preencher_tabela();
            
            JOptionPane.showMessageDialog(null, "Estoque Baixo! Só um aviso!!", "Aviso Estoque", 1);

        }else{
            p1.setQauntidade(qt);

            ItemVendas_controller item = new ItemVendas_controller();
            item.salvar(iv);
            
            Produtos_controller p = new Produtos_controller();
            p.alterar(p1);
            
            preencher_tabela();
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Vendas_model ven = new Vendas_model();
            ven.setIdvenda(Integer.parseInt(tfCod.getText()));
            ven.setIdCliente(id_cli);
            try { 
                DateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
                ven.setData(new java.sql.Date(((java.util.Date) formatador.parse(jFormattedTextField1.getText())).getTime()));
            } catch (ParseException ex) {
                   Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
            }
            ven.setTotalpagar(Double.parseDouble(tfVT.getText()));
            System.out.println(ven.getTotalpagar());

            Vendas_controller ven2 = new Vendas_controller();
            ven2.alterar(ven);


             JOptionPane.showMessageDialog(null, "Venda Finalizada!!!!", "Vendas", 1);
             
            dispose();
            Menu x = new Menu();
            x.setVisible(true);
            cont=0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVTActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        Menu x = new Menu();
        x.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
     public void busca()
    {
        Vendas_controller vend = new Vendas_controller();
        c.conectar();
        cod = vend.listar();
        tfCod.setText(String.valueOf(cod+1));
    }

    public void busca2()
    {

        Clientes_controller t = new Clientes_controller();
      
        List<Clientes_model> lista_cli = (List<Clientes_model>) t.listar_dados();
        
        for(int i=0; i<lista_cli.size();i++)
        {
            cbCliente.addItem(lista_cli.get(i).getNomeCliente());
            
        }


    }

     public void busca3()
    {

        Produtos_controller t = new Produtos_controller();
        List<Produtos_model> lista_prod = (List<Produtos_model>) t.listar_dados();

        for(int i=0; i<lista_prod.size();i++)
        {
            if(lista_prod.get(i).getQauntidade() > 0){
                cbProduto.addItem(lista_prod.get(i).getNomeProduto());
            }
        }

    }

     public int busca4()
    {
 
        Produtos_controller t = new Produtos_controller();

        List<Produtos_model> lista_produto = (List<Produtos_model>) t.listar_dados();
        
        for(int i=0; i<lista_produto.size();i++)
        {
            if(cbProduto.getSelectedItem().toString().equals(lista_produto.get(i).getNomeProduto()))
            {
                id = lista_produto.get(i).getIdProduto();
                totalparc = Integer.parseInt(tfQtde.getText())* lista_produto.get(i).getValor_venda();
                totalpag = totalpag + totalparc;
                tfVT.setText(String.valueOf(totalpag));
                
                quant = lista_produto.get(i).getQauntidade();
                
                item_prod it = new item_prod();

                it.setDescProduto(lista_produto.get(i).getNomeProduto());
                it.setPreco(lista_produto.get(i).getValor_venda());
                it.setQtde(Integer.parseInt(tfQtde.getText()));
                it.setTotal(totalparc);
                list_pro.add(it);
            }
        }
        return id;

    }
     
     
  public int busca5()
    {
        Clientes_controller t = new Clientes_controller();
        List<Clientes_model> lista_cliente = (List<Clientes_model>) t.listar_dados();

        for(int i=0; i<lista_cliente.size();i++)
        {
            if(cbCliente.getSelectedItem().toString().equals(lista_cliente.get(i).getNomeCliente()))
            {
                id_cli = lista_cliente.get(i).getIdCliente();
            }
        }
        return id_cli;
    }
  
    public void preencher_tabela() {
         DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
         modelo.setRowCount(0);

         for(int a=0; a<list_pro.size();a++){
            modelo.addRow(new Object[]{
              list_pro.get(a).getDescProduto(),
              list_pro.get(a).getQtde(),
              list_pro.get(a).getPreco(),
              list_pro.get(a).getTotal()
         });
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfCod;
    private javax.swing.JTextField tfQtde;
    private javax.swing.JTextField tfVT;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        tfQtde.setText("");
        tfVT.setText("");
        jFormattedTextField1.setText("");
        cbCliente.setSelectedIndex(0);
        cbProduto.setSelectedIndex(0);
        tfCod.setText("");
    }
}
